development:
  server_address: ['192.168.100.11', '192.168.100.12', '192.168.100.14', '192.168.100.24']
  server_name: infsphr.info
  nginx_server_host: 127.0.0.1
  nginx_server_login: user
  nginx_server_password:
  nginx_tcp_config_path: /Users/azirumga/Test
  nginx_http_config_path: /Users/azirumga/Test

test:
  server_address: ['192.168.100.11', '192.168.100.12', '192.168.100.14', '192.168.100.24']
  server_name: infsphr.info
  nginx_server_host: localhost
  nginx_server_login: azirumga
  nginx_server_password: iselPodij
  nginx_tcp_config_path: /Users/azirumga/Test/stream
  nginx_http_config_path: /Users/azirumga/Test/http

production:
  server_address: ['192.168.100.11', '192.168.100.12', '192.168.100.14', '192.168.100.24']
  retranslator_port: 31072
  server_name: infsphr.info
  nginx_server_host: 127.0.0.1
  nginx_server_login: user
  nginx_server_password:
  nginx_tcp_config_path: /etc/nginx/conf.d/stream
  nginx_http_config_path: /etc/nginx/conf.d/http
